import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <div className="w-full min-h-screen flex justify-center bg-black">
          <div className="w-full">
            <nav className="w-full bg-gray-800  fixed top-0 z-100">
              <div className="max-w-[1600px] mx-auto flex justify-around py-4 px-6 text-white font-bold">
                <Link href="/">홈</Link>
                <Link href="/champions">챔피언 목록</Link>
                <Link href="/items">아이템 목록</Link>
                <Link href="/rotation">챔피언 로테이션</Link>
              </div>
            </nav>
            <main className="flex justify-center mt-16 max-w-[1600px] mx-auto px-6 text-white">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
